# Generated by Django 4.0.2 on 2022-02-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productmodel_image_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='catagory',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('wahmen', 'women'), ('kid', "kid's")], max_length=6, null=True),
        ),
    ]
