# Generated by Django 4.0.2 on 2022-02-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_alter_productmodel_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='catagory',
            new_name='category',
        ),
    ]
