# Generated by Django 4.0.2 on 2022-02-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_catagory_productmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sub_cat',
            field=models.ManyToManyField(to='core.sub_cat'),
        ),
    ]
