# Generated by Django 4.0.2 on 2022-02-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sub_cat_category_sub_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_cat',
            name='url',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
