# Generated by Django 4.0.2 on 2022-02-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sub_cat_url_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_cat',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
